### ISSUE TITLE
Thailand, bugged "Blend In" spot

### ISSUE THREAD

**Issue by leet-it-b** [edisleado/Hitman-Bug-Tracker#58]
Firstly - there is no "gardener" disguise on the level. Only "groundskeeper".
Secondly - you can blending here in the wrong disguise.
![20160817011431_1](https://cloud.githubusercontent.com/assets/20925661/17718430/814bf584-641c-11e6-9526-daa18a6a90ff.jpg)
![20160817011816_1](https://cloud.githubusercontent.com/assets/20925661/17718436/844f4d8a-641c-11e6-994d-a129fd0f85a5.jpg)

**Comment by HMBM47** [comment]
This particular one has been fixed BUT the one just on the other side of the planter is broken. (Or perhaps it just changed sides?) One difference is it correctly displays "groundskeeper" instead of "gardener".
![blendspot00](https://cloud.githubusercontent.com/assets/20890580/18876557/086f47a0-847f-11e6-85f9-2ec9f07987bf.png)
![blendspot01](https://cloud.githubusercontent.com/assets/20890580/18876558/08725fc6-847f-11e6-8810-4f559661b675.jpg)
![blendspot01](https://cloud.githubusercontent.com/assets/20890580/18876585/26cb1260-847f-11e6-885c-650aad342be7.jpg)

**Comment by HMBM47** [comment]
Fixed. 
Rake is always there and cannot be used unless dressed in the proper disguise.
