### ISSUE TITLE
Completed challenges don't unlock upon finishing the session

### ISSUE THREAD

**Issue by edisleado** [edisleado/Hitman-Bug-Tracker#7]
Challenges unlocked within a session are not officially registered by the game until the subsequent playthrough of the relevant mission.

This problem may have popped up around the time challenge behaviour was changed so that players no longer needed to actually finish a mission to have challenges unlock.

**Comment by leet-it-b** [comment]
Fixed for me.

**Comment by HMBM47** [comment]
I believe this has been fixed.
I think it was fixed with the release of the Fortune Teller challenge pack. That's when I noticed those challenges unlocked right away. Plus, in creating a new Steam account around the same time, the challenges popped up at the end of the level, and the rewards associated with them unlocked when they were supposed to.
I had absolutely no issues with Colorado reaching 20/20.
